apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optaplanner # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/name: optaplanner
#   app.kubernetes.io/instance: optaplanner
#   app.kubernetes.io/component: scheduling-engine
#   app.kubernetes.io/part-of: atomic-stack # Or your specific application/project name

# Optional: Add common annotations
# commonAnnotations:
#   note: "Optaplanner service base configuration"
